name: ASP .NET CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  ci-pipe:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Dependencies
      working-directory: ./PostService
      run: dotnet restore
    - name: Build
      working-directory: ./PostService
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./PostService
      run: dotnet test --no-build --verbosity normal
